#!/bin/sh

set -e

echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check
echo '+cargo clippy --all-features --workspace -- -D warnings'
cargo clippy --all-features --workspace -- -D warnings
echo '+cargo test --all'
cargo test --all

